name: SARIF Analysis

on:
  push:
    branches:
      - master

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload SARIF file and trigger analysis
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codeql_results_2/cpp-results.sarif

